modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="mineprocess"
version="1.0.0"
displayName="MineProcess"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
authors="STS15"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
A processing mod by STS15
'''

[[dependencies.mineprocess]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.mineprocess]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
